// packages/ui/src/lib/components/core/dropdown.svelte
<script lang="ts">
  import * as Combobox from "$lib/components/core/combobox/index.js";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "value" | "id"> {
    value?: string;
    id?: string;
    open?: boolean;
    disabled?: boolean;
    placeholder?: string;
    onValueChange?: (value: string) => void;
    onOpenChange?: (open: boolean) => void;
  }

  let {
    value = $bindable(""),
    open = $bindable(false),
    disabled = false,
    placeholder = "Select an option",
    onValueChange = undefined,
    onOpenChange = undefined,
    class: className = undefined,
    children,
    ...restProps
  }: Props = $props();
</script>

<Combobox.Root
  bind:value
  bind:open
  {disabled}
  openOnClick={true}
  onOpenChange={(details) => onOpenChange?.(details.open)}
  {...restProps}
>
  <Combobox.Input
    readonly
    {placeholder}
    showTrigger
    class="cursor-pointer caret-transparent"
    onkeydown={(e) => {
      if (e.key === "Enter" || e.key === " ") {
        if (!open) {
          e.preventDefault();
          open = true;
        } else if (e.key === " ") {
          // Prevent scroll when open, as this is a dropdown and Space should select
          e.preventDefault();
          // Find the currently highlighted item and click it to select
          const item = document.querySelector(
            '[data-highlighted][data-slot="combobox-item"]',
          );
          if (item instanceof HTMLElement) item.click();
        }
      }
    }}
  />

  <Combobox.Content>
    <Combobox.List>
      {@render children?.()}
    </Combobox.List>
  </Combobox.Content>
</Combobox.Root>

// packages/ui/src/components/Dropdown.tsx
import { splitProps, type JSX } from "solid-js";
import {
  Combobox,
  ComboboxContent,
  ComboboxInput,
  ComboboxList,
  type ComboboxProps,
} from "./Combobox";
import { cn } from "../lib/cn";

type ComboboxRootProps = ComboboxProps;

export interface DropdownProps
  extends Omit<
    ComboboxRootProps,
    "class" | "multiple" | "onOpenChange" | "onValueChange" | "value"
  > {
  readonly class?: string;
  readonly inputClass?: string;
  readonly open?: boolean;
  readonly placeholder?: string;
  readonly size?: "sm" | "default" | "lg";
  readonly value?: string;
  readonly onOpenChange?: (open: boolean) => void;
  readonly onValueChange?: (value: string) => void;
}

export function Dropdown(props: DropdownProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "children",
    "class",
    "inputClass",
    "onOpenChange",
    "onValueChange",
    "open",
    "placeholder",
    "size",
    "value",
  ]);
  const value = () => {
    const current = local.value;
    return current && current.length > 0 ? [current] : [];
  };
  let handledPrimitiveValueChange = false;

  return (
    <Combobox
      {...rest}
      class={cn("dropdown", local.class)}
      inputBehavior="none"
      open={local.open}
      openOnClick
      onOpenChange={(details) => local.onOpenChange?.(details.open)}
      onValueChange={(details) => {
        handledPrimitiveValueChange = true;
        queueMicrotask(() => {
          handledPrimitiveValueChange = false;
        });
        local.onValueChange?.(details.value[0] ?? "");
      }}
      value={local.value === undefined ? undefined : value()}
    >
      <ComboboxInput
        class={cn("dropdown__input", local.inputClass)}
        placeholder={local.placeholder ?? "Select an option"}
        readOnly
        showClear={false}
        showTrigger
        size={local.size ?? "default"}
        onKeyDown={(event) => {
          if (event.key !== "Enter" && event.key !== " ") return;
          if (event.key === " ") event.preventDefault();

          const highlighted = document.querySelector<HTMLElement>(
            '[data-highlighted][data-slot="combobox-item"]',
          );
          if (highlighted && local.open) {
            highlighted.click();
          }
        }}
      />
      <ComboboxContent>
        <ComboboxList
          onClick={(event) => {
            if (handledPrimitiveValueChange) return;
            const item = (event.target as HTMLElement).closest<HTMLElement>(
              "[data-slot='combobox-item']",
            );
            const nextValue = item?.getAttribute("data-value");
            if (nextValue !== null && nextValue !== undefined) {
              local.onValueChange?.(nextValue);
            }
          }}
        >
          {local.children}
        </ComboboxList>
      </ComboboxContent>
    </Combobox>
  );
}
