// packages/ui/src/lib/components/core/separator.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    orientation?: "horizontal" | "vertical";
    ref?: HTMLDivElement;
  }

  let {
    class: className,
    orientation = "horizontal",
    ref = $bindable(),
    ...props
  }: Props = $props();
</script>

<div
  bind:this={ref}
  class={cn(
    "shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:w-px data-[orientation=vertical]:not-[[class^='h-']]:not-[[class*='_h-']]:self-stretch",
    className,
  )}
  data-slot="separator"
  data-orientation={orientation}
  {...props}
></div>

// packages/ui/src/components/Separator.tsx
import { splitProps, type JSX } from "solid-js";
import { cn } from "../lib/cn";

export interface SeparatorProps extends JSX.HTMLAttributes<HTMLDivElement> {
  readonly decorative?: boolean;
  readonly orientation?: "horizontal" | "vertical";
}

export function Separator(props: SeparatorProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "class",
    "decorative",
    "orientation",
  ]);
  const orientation = () => local.orientation ?? "horizontal";

  return (
    <div
      {...rest}
      aria-orientation={orientation()}
      class={cn("separator", `separator--${orientation()}`, local.class)}
      data-slot="separator"
      role={(local.decorative ?? true) ? "none" : "separator"}
    />
  );
}
